 
spring:
  application:
    name: kafka-consumer-application
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
          - localhost:9092
      bindings:
        employee-input:
         binder: kafka
         destination: employee-details-topic
         content-type: application/json
         group: employee-group
         
server:
  port: 9082


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9093/eureka/